"""Mypy check
Use Mypy project (github.com/python/mypy) to perform static type check ing of your code.
Play around a little bit with Mypy, go through results and reports generated by running the mypy,
perform refactoring based on the mentioned results."""